# E-Commerce Customer Churn Patterns and Customer Retention Analysis

**Project Domain:** E-Commerce Analytics

**Phase 1:** Project Proposal and Initial Dataset Inspection

## 1. Project Overview

Customer churn occurs when customers stop purchasing products or discontinue their relationship with an e-commerce business. Understanding customer churn is important for identifying customers who may leave and developing suitable customer retention strategies.

This project focuses on analyzing e-commerce customer churn patterns, identifying customer characteristics associated with churn, and exploring factors related to customer retention. Python and its data analysis libraries will be used to inspect, clean, analyze, and visualize the dataset.

## 2. Business Problem

E-commerce businesses may experience customer loss because of poor customer satisfaction, reduced purchasing activity, service issues, or other factors. Losing customers can affect sales, revenue, and long-term business growth.

Therefore, analyzing customer churn data can help identify patterns in customer behavior and highlight factors associated with customer loss. The findings may support better-informed customer retention decisions.

## 3. Project Objectives

The main objectives of this project are:

1. To inspect and understand the e-commerce customer churn dataset.
2. To identify the overall customer churn pattern.
3. To examine customer characteristics associated with churn.
4. To analyze the relationship between purchasing behavior and customer churn.
5. To explore the relationship between customer satisfaction and churn.
6. To identify customer segments with different churn patterns.
7. To visualize important findings using Python.
8. To provide data-driven insights that may support customer retention strategies.

## 4. Dataset Information

**Dataset Name:** E-Commerce Customer Churn Dataset

**Source:** Kaggle

**Dataset Link:** https://www.kaggle.com/datasets/datascikhan/e-commerce-customer-churn-2026

**Description:**

The dataset contains 48 columns related to customer information, purchasing behavior, satisfaction, churn status, marketing engagement, customer value, and retention activities. These variables will be used to explore customer churn patterns and identify characteristics associated with customer retention.

### Dataset Variables

The dataset includes the following categories of variables:

1. **Customer Information:** `churn_id`, `customer_id`, `customer_segment`, `customer_country`, `customer_city`
2. **Churn Information:** `is_churned`, `churn_flag`, `churn_date`, `days_since_churn`, `churn_reason`, `churn_category`
3. **Churn Risk Indicators:** `churn_risk_score`, `churn_probability`, `is_high_risk_customer`, `predicted_churn`, `churn_risk_category`, `churn_rate_indicator`
4. **Purchasing and Subscription Information:** `subscription_type`, `customer_age_months`, `total_spend_usd`, `avg_order_value_usd`, `num_purchases`, `days_since_last_purchase`
5. **Customer Satisfaction and Support:** `satisfaction_score`, `satisfaction_level`, `support_tickets`, `returns_count`, `support_interactions`, `last_support_channel`, `feedback_score`
6. **Customer Value and Engagement:** `customer_lifetime_value_usd`, `engagement_level`, `loyalty_score`, `customer_value_category`, `customer_health_score`, `customer_health_category`
7. **Marketing and Referrals:** `marketing_emails_sent`, `marketing_emails_opened`, `marketing_emails_clicked`, `marketing_conversions`, `social_media_engagement`, `referral_count`
8. **Retention and Revenue:** `prevention_method`, `customer_retention_cost_usd`, `recovery_revenue_usd`, `churn_revenue_impact_usd`, `retention_probability`
9. **Temporal Information:** `dataset_year`

The actual number of rows and the data types of the variables will be verified during the initial dataset inspection.

## 5. Planned Analysis

The following analyses are planned for the project:

1. **Dataset Inspection:** Examine the dataset structure, dimensions, column names, and data types.
2. **Data Quality Assessment:** Identify missing values, duplicate records, and potential inconsistencies.
3. **Customer Churn Analysis:** Examine the distribution of churned and non-churned customers.
4. **Customer Segmentation:** Compare churn patterns across available customer segments.
5. **Purchasing Behavior Analysis:** Explore the relationship between purchasing activity, spending, and churn.
6. **Customer Satisfaction Analysis:** Examine customer satisfaction and support-related variables in relation to churn.
7. **Data Visualization:** Create suitable charts to communicate the findings.
8. **Customer Retention Insights:** Summarize patterns that may help inform customer retention strategies.

The analyses will be selected according to the variables available and the quality of the dataset.

## 6. Scope and Limitations

### Scope

* Inspection and preparation of the e-commerce customer churn dataset.
* Exploratory data analysis using Python.
* Examination of customer churn patterns and related customer characteristics.
* Visualization of findings and identification of potential retention opportunities.

### Limitations

* The analysis depends on the completeness and accuracy of the available dataset.
* Observational relationships do not necessarily establish cause and effect.
* The dataset's collection method and definitions of churn must be reviewed.
* Any precomputed churn predictions or risk scores will be examined carefully before being used as evidence.
* Findings may not represent all e-commerce businesses or customer populations.

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
DATA_PATH = r"C:\Users\DELL\Documents\Ecommerce-Customer-Churn-Analysis\data\dataset.csv"

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        "Dataset not found. Please check the folder path "
        "and CSV filename."
    )

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head()

Dataset loaded successfully!
Number of rows: 50000
Number of columns: 48

,churn_id,customer_id,customer_segment,customer_country,customer_city,is_churned,churn_flag,churn_date,days_since_churn,churn_reason,...,customer_retention_cost_usd,recovery_revenue_usd,dataset_year,churn_rate_indicator,customer_value_category,churn_risk_category,churn_revenue_impact_usd,customer_health_score,customer_health_category,retention_probability
0,CHURN-000001,CUST-020712,Consumer,Australia,Brisbane,Yes,1,2026-05-18 00:00:00,23,Found Alternative,...,29.33,346.60,2026,Medium,High Value,Medium,10351.348,75,Good,0.10
1,CHURN-000002,CUST-044206,Small Business,Saudi Arabia,Khobar,No,0,Not Applicable,0,Not Applicable,...,49.22,403.14,2026,Low,High Value,Low,0.000,100,Excellent,0.66
2,CHURN-000003,CUST-024093,Small Business,Mexico,Leon,No,0,Not Applicable,0,Not Applicable,...,198.06,4.20,2026,Low,High Value,Low,0.000,100,Excellent,0.76
3,CHURN-000004,CUST-037777,Enterprise,Saudi Arabia,Jeddah,No,0,Not Applicable,0,Not Applicable,...,190.31,222.46,2026,Low,High Value,Very Low,0.000,100,Excellent,0.98
4,CHURN-000005,CUST-016248,Premium,Pakistan,Multan,Yes,1,2026-05-28 00:00:00,7,Poor Customer Service,...,26.49,489.02,2026,Medium,High Value,Medium,14212.088,80,Good,0.10

In [6]:
df.head()

,churn_id,customer_id,customer_segment,customer_country,customer_city,is_churned,churn_flag,churn_date,days_since_churn,churn_reason,...,customer_retention_cost_usd,recovery_revenue_usd,dataset_year,churn_rate_indicator,customer_value_category,churn_risk_category,churn_revenue_impact_usd,customer_health_score,customer_health_category,retention_probability
0,CHURN-000001,CUST-020712,Consumer,Australia,Brisbane,Yes,1,2026-05-18 00:00:00,23,Found Alternative,...,29.33,346.60,2026,Medium,High Value,Medium,10351.348,75,Good,0.10
1,CHURN-000002,CUST-044206,Small Business,Saudi Arabia,Khobar,No,0,Not Applicable,0,Not Applicable,...,49.22,403.14,2026,Low,High Value,Low,0.000,100,Excellent,0.66
2,CHURN-000003,CUST-024093,Small Business,Mexico,Leon,No,0,Not Applicable,0,Not Applicable,...,198.06,4.20,2026,Low,High Value,Low,0.000,100,Excellent,0.76
3,CHURN-000004,CUST-037777,Enterprise,Saudi Arabia,Jeddah,No,0,Not Applicable,0,Not Applicable,...,190.31,222.46,2026,Low,High Value,Very Low,0.000,100,Excellent,0.98
4,CHURN-000005,CUST-016248,Premium,Pakistan,Multan,Yes,1,2026-05-28 00:00:00,7,Poor Customer Service,...,26.49,489.02,2026,Medium,High Value,Medium,14212.088,80,Good,0.10

In [7]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 50000
Number of columns: 48

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   churn_id                     50000 non-null  object
 1   customer_id                  50000 non-null  object
 2   customer_segment             50000 non-null  object
 3   customer_country             50000 non-null  object
 4   customer_city                50000 non-null  object
 5   is_churned                   50000 non-null  object
 6   churn_flag                   50000 non-null  int64
 7   churn_date                   50000 non-null  object
 8   days_since_churn             50000 non-null  int64
 9   churn_reason                 50000 non-null  object
 10  churn_category               50000 non-null  object
 11  churn_risk_score             50000 non-null  int64
 12  churn_probability            50000 non-null  float64
 13  subscription_type            36858 non-null  object
 14  customer_age_months          50000 non-null  int64
 15  total_spend_usd              50000 non-null  float64
 16  avg_order_value_usd          50000 non-null  float64
 17  num_purchases                50000 non-null  int64
 18  satisfaction_score           50000 non-null  int64
 19  satisfaction_level           50000 non-null  object
 20  support_tickets              50000 non-null  int64
 21  returns_count                50000 non-null  int64
 22  days_since_last_purchase     50000 non-null  int64
 23  customer_lifetime_value_usd  50000 non-null  float64
 24  engagement_level             50000 non-null  object
 25  prevention_method            13126 non-null  object
 26  support_interactions         50000 non-null  int64
 27  last_support_channel         50000 non-null  object
 28  feedback_score               50000 non-null  int64
 29  loyalty_score                50000 non-null  float64
 30  marketing_emails_sent        50000 non-null  int64
 31  marketing_emails_opened      50000 non-null  int64
 32  marketing_emails_clicked     50000 non-null  int64
 33  marketing_conversions        50000 non-null  int64
 34  social_media_engagement      34996 non-null  object
 35  referral_count               50000 non-null  int64
 36  is_high_risk_customer        50000 non-null  object
 37  predicted_churn              50000 non-null  object
 38  customer_retention_cost_usd  50000 non-null  float64
 39  recovery_revenue_usd         50000 non-null  float64
 40  dataset_year                 50000 non-null  int64
 41  churn_rate_indicator         50000 non-null  object
 42  customer_value_category      50000 non-null  object
 43  churn_risk_category          50000 non-null  object
 44  churn_revenue_impact_usd     50000 non-null  float64
 45  customer_health_score        50000 non-null  int64
 46  customer_health_category     50000 non-null  object
 47  retention_probability        50000 non-null  float64
dtypes: float64(9), int64(18), object(21)
memory usage: 18.3+ MB

In [10]:
df.shape

(50000, 48)

In [11]:
df.columns

Index(['churn_id', 'customer_id', 'customer_segment', 'customer_country',
       'customer_city', 'is_churned', 'churn_flag', 'churn_date',
       'days_since_churn', 'churn_reason', 'churn_category',
       'churn_risk_score', 'churn_probability', 'subscription_type',
       'customer_age_months', 'total_spend_usd', 'avg_order_value_usd',
       'num_purchases', 'satisfaction_score', 'satisfaction_level',
       'support_tickets', 'returns_count', 'days_since_last_purchase',
       'customer_lifetime_value_usd', 'engagement_level', 'prevention_method',
       'support_interactions', 'last_support_channel', 'feedback_score',
       'loyalty_score', 'marketing_emails_sent', 'marketing_emails_opened',
       'marketing_emails_clicked', 'marketing_conversions',
       'social_media_engagement', 'referral_count', 'is_high_risk_customer',
       'predicted_churn', 'customer_retention_cost_usd',
       'recovery_revenue_usd', 'dataset_year', 'churn_rate_indicator',
       'customer_value_category', 'churn_risk_category',
       'churn_revenue_impact_usd', 'customer_health_score',
       'customer_health_category', 'retention_probability'],
      dtype='object')

In [12]:
df.dtypes

churn_id                        object
customer_id                     object
customer_segment                object
customer_country                object
customer_city                   object
is_churned                      object
churn_flag                       int64
churn_date                      object
days_since_churn                 int64
churn_reason                    object
churn_category                  object
churn_risk_score                 int64
churn_probability              float64
subscription_type               object
customer_age_months              int64
total_spend_usd                float64
avg_order_value_usd            float64
num_purchases                    int64
satisfaction_score               int64
satisfaction_level              object
support_tickets                  int64
returns_count                    int64
days_since_last_purchase         int64
customer_lifetime_value_usd    float64
engagement_level                object
prevention_method               object
support_interactions             int64
last_support_channel            object
feedback_score                   int64
loyalty_score                  float64
marketing_emails_sent            int64
marketing_emails_opened          int64
marketing_emails_clicked         int64
marketing_conversions            int64
social_media_engagement         object
referral_count                   int64
is_high_risk_customer           object
predicted_churn                 object
customer_retention_cost_usd    float64
recovery_revenue_usd           float64
dataset_year                     int64
churn_rate_indicator            object
customer_value_category         object
churn_risk_category             object
churn_revenue_impact_usd       float64
customer_health_score            int64
customer_health_category        object
retention_probability          float64
dtype: object

In [13]:
print("Total number of elements:", df.size)

Total number of elements: 2400000

In [14]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values[missing_values > 0])

print("\nTotal missing values:", df.isnull().sum().sum())

Missing values in each column:
subscription_type          13142
prevention_method          36874
social_media_engagement    15004
dtype: int64

Total missing values: 65020

In [15]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [16]:
df.describe()

,churn_flag,days_since_churn,churn_risk_score,churn_probability,customer_age_months,total_spend_usd,avg_order_value_usd,num_purchases,satisfaction_score,support_tickets,...,marketing_emails_opened,marketing_emails_clicked,marketing_conversions,referral_count,customer_retention_cost_usd,recovery_revenue_usd,dataset_year,churn_revenue_impact_usd,customer_health_score,retention_probability
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.0,50000.000000,50000.000000,50000.000000
mean,0.413060,37.193620,41.159080,0.411591,30.134580,25039.361048,2263.123812,24.505700,3.008040,9.405480,...,12.211740,12.25672,3.118120,9.493440,99.903609,249.263203,2026.0,4135.546160,88.604100,0.447838
std,0.492388,55.352953,24.709309,0.247093,16.893094,14401.590909,4797.349786,14.433401,1.420569,5.763646,...,11.100082,11.13755,2.845841,5.768815,57.774781,144.579983,0.0,6158.312439,17.484367,0.332232
min,0.000000,0.000000,0.000000,0.000000,1.000000,0.720000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.020000,2026.0,0.000000,25.000000,0.020000
25%,0.000000,0.000000,22.000000,0.220000,16.000000,12578.125000,469.940000,12.000000,2.000000,4.000000,...,3.000000,3.00000,1.000000,4.000000,49.767500,124.177500,2026.0,0.000000,80.000000,0.100000
50%,0.000000,0.000000,40.000000,0.400000,30.000000,25034.390000,982.480000,24.000000,3.000000,9.000000,...,9.000000,9.00000,2.000000,10.000000,100.105000,248.910000,2026.0,0.000000,100.000000,0.460000
75%,1.000000,72.000000,59.000000,0.590000,45.000000,37579.255000,1912.195000,37.000000,4.000000,14.000000,...,19.000000,19.00000,5.000000,14.000000,149.802500,374.232500,2026.0,7923.600000,100.000000,0.750000
max,1.000000,179.000000,100.000000,1.000000,59.000000,49998.300000,49980.820000,49.000000,5.000000,19.000000,...,49.000000,49.00000,9.000000,19.000000,200.000000,500.000000,2026.0,19999.320000,100.000000,1.000000

In [17]:
df.describe()

,churn_flag,days_since_churn,churn_risk_score,churn_probability,customer_age_months,total_spend_usd,avg_order_value_usd,num_purchases,satisfaction_score,support_tickets,...,marketing_emails_opened,marketing_emails_clicked,marketing_conversions,referral_count,customer_retention_cost_usd,recovery_revenue_usd,dataset_year,churn_revenue_impact_usd,customer_health_score,retention_probability
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.0,50000.000000,50000.000000,50000.000000
mean,0.413060,37.193620,41.159080,0.411591,30.134580,25039.361048,2263.123812,24.505700,3.008040,9.405480,...,12.211740,12.25672,3.118120,9.493440,99.903609,249.263203,2026.0,4135.546160,88.604100,0.447838
std,0.492388,55.352953,24.709309,0.247093,16.893094,14401.590909,4797.349786,14.433401,1.420569,5.763646,...,11.100082,11.13755,2.845841,5.768815,57.774781,144.579983,0.0,6158.312439,17.484367,0.332232
min,0.000000,0.000000,0.000000,0.000000,1.000000,0.720000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.020000,2026.0,0.000000,25.000000,0.020000
25%,0.000000,0.000000,22.000000,0.220000,16.000000,12578.125000,469.940000,12.000000,2.000000,4.000000,...,3.000000,3.00000,1.000000,4.000000,49.767500,124.177500,2026.0,0.000000,80.000000,0.100000
50%,0.000000,0.000000,40.000000,0.400000,30.000000,25034.390000,982.480000,24.000000,3.000000,9.000000,...,9.000000,9.00000,2.000000,10.000000,100.105000,248.910000,2026.0,0.000000,100.000000,0.460000
75%,1.000000,72.000000,59.000000,0.590000,45.000000,37579.255000,1912.195000,37.000000,4.000000,14.000000,...,19.000000,19.00000,5.000000,14.000000,149.802500,374.232500,2026.0,7923.600000,100.000000,0.750000
max,1.000000,179.000000,100.000000,1.000000,59.000000,49998.300000,49980.820000,49.000000,5.000000,19.000000,...,49.000000,49.00000,9.000000,19.000000,200.000000,500.000000,2026.0,19999.320000,100.000000,1.000000

## Initial Dataset Observations

After loading the dataset, I confirmed that it contains **50,000 records and 48 columns**, with a total of 2,400,000 data elements. The dataset includes information about customer demographics, purchasing behavior, customer satisfaction, churn status, marketing engagement, and customer retention.

During the initial inspection, I identified **65,020 missing values** across three columns: `subscription_type` (13,142), `prevention_method` (36,874), and `social_media_engagement` (15,004). No duplicate rows were detected in the dataset.

At this stage, I have completed an initial inspection of the dataset. A closer examination of the data types, missing and unknown values, and distributions of important variables will be carried out during the next stages of the project. The reasons for the missing values will also be investigated before deciding how to handle them.